export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_PRODUCTS_DOWNLOAD = 'START_PRODUCTS_DOWNLOAD';
export const PRODUCTS_DOWNLOAD_SUCCESS = 'START_PRODUCTS_DOWNLOAD_SUCCESS';
export const PRODUCTS_DOWNLOAD_ERROR = 'START_PRODUCTS_DOWNLOAD_ERROR';